# Generated by Django 6.0.4 on 2026-05-31 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rubros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesionales/')),
                ('atiende_urgencias', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='profesionales.rubro')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.zona')),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
                'ordering': ['nombre'],
            },
        ),
    ]
