# Generated by Django 6.0.4 on 2026-05-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
