# Generated by Django 6.0.4 on 2026-06-03 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_profesional_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=10)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de aviso',
                'verbose_name_plural': 'Categorías de avisos',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avisos/')),
                ('whatsapp', models.CharField(max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='profesionales.categoriaaviso')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-fecha_desde'],
            },
        ),
    ]
