# Generated by Django 6.0.4 on 2026-06-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_fotoaviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=100, verbose_name='Tu nombre')),
                ('email_autor', models.EmailField(max_length=254, verbose_name='Tu email (no se mostrará públicamente)')),
                ('estrellas', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puntuación')),
                ('comentario', models.TextField(verbose_name='Tu opinión')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprobada', models.BooleanField(default=False, verbose_name='Aprobada')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='profesionales.profesional')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha'],
            },
        ),
    ]
